package sbnz.app;

import sbnz.app.model.*;
import sbnz.app.fact.*;
import java.util.List;

declare enum PopularityType
   POPULAR, UNPOPULAR, INDETERMINABLE;
end

declare Popularity
	locationId: long
	type: PopularityType
end

query hasPercentageOfPositiveRatingsInRange(long $locationId, int $minPercentage, int $maxPercentage)
	$l : Location(id == $locationId)
	$ratings : List(size > 0) from collect(Rating(location.id == $l.id))
	Number(intValue / $ratings.size * 100 >= $minPercentage, intValue / $ratings.size * 100 <= $maxPercentage)
	from accumulate(Rating($rating:this, type == RatingType.LIKE) from $ratings, count($rating))
end

rule "location popular if it has more than 80% of positive ratings"
	when
		$l : Location($locationId : id)
		not Popularity(locationId == $locationId)
		hasPercentageOfPositiveRatingsInRange($locationId, Constants.POPULAR_MIN, 100;)
	then
		System.out.println("Location with name " + $l.getName() + " is popular");
		insert(new Popularity($locationId, PopularityType.POPULAR));
end

rule "location unpopular if it has less than 20% of positive ratings"
	when
		$l : Location($locationId : id)
		not Popularity(locationId == $locationId)
		hasPercentageOfPositiveRatingsInRange($locationId, 0, Constants.UNPOPULAR_MAX;)
	then
		System.out.println("Location with name " + $l.getName() + " is unpopular");
		insert(new Popularity($locationId, PopularityType.UNPOPULAR));
end

rule "location popular if it has more than 70% of positive ratings and rating count above average"
	when
		$l : Location($locationId : id)
		not Popularity(locationId == $locationId)
		$avgRatings : Number() from accumulate(
								Location($id : id) and
								$ratings : List() from collect (Rating(location.id == $id)),
								average($ratings.size())
							)
		List(size > $avgRatings.intValue()) from collect(Rating(location.id == $locationId))
		hasPercentageOfPositiveRatingsInRange($locationId, Constants.POPULAR_MIN_WHEN_ABOVE_AVERAGE, 100;)
	then
		System.out.println("Location with name " + $l.getName() + " is popular");
		insert(new Popularity($locationId, PopularityType.POPULAR));
end

rule "location unpopular if it has less than 30% of positive ratings and rating count above average"
	when
		$l : Location($locationId : id)
		not Popularity(locationId == $locationId)
		$avgRatings : Number() from accumulate(
								Location($id : id) and
								$ratings : List() from collect (Rating(location.id == $id)),
								average($ratings.size())
							)
		List(size > $avgRatings.intValue()) from collect(Rating(location.id == $locationId))
		hasPercentageOfPositiveRatingsInRange($locationId, 0, Constants.UNPOPULAR_MAX_WHEN_ABOVE_AVERAGE;)
	then
		System.out.println("Location with name " + $l.getName() + " is unpopular");
		insert(new Popularity($locationId, PopularityType.UNPOPULAR));
end

rule "location's popularity is indeterminable if it has no ratings"
	when
		$l : Location($locationId : id)
		not Popularity(locationId == $locationId)
		not Rating(location.id == $locationId)
	then
		System.out.println("Location with name " + $l.getName() +" popularity is indeterminable");
		insert(new Popularity($locationId, PopularityType.INDETERMINABLE));
end

rule "location's popularity is indeterminable if no other rule has been activated"
salience -1
	when
		$l : Location($locationId : id)
		not Popularity(locationId == $locationId)
	then
		System.out.println("Location with name " + $l.getName() +" popularity is indeterminable");
		insert(new Popularity($locationId, PopularityType.INDETERMINABLE));
end